name: CI

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch: { }

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 17 (Temurin) with Maven cache
                uses: actions/setup-java@v4
                with:
                    distribution: temurin
                    java-version: "17"
                    cache: maven
            -   name: Code style check (Spotless)
                run: mvn -B -ntp spotless:check
            -   name: Lint (Checkstyle)
                run: mvn -B -ntp -DskipTests verify
            -   name: Build & Test
                run: mvn -B -ntp verify
            -   name: Upload test reports (always)
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: surefire-reports
                    path: |
                        **/target/surefire-reports/**
                        **/target/failsafe-reports/**
                    if-no-files-found: ignore

