name: Deploy to VM

on:
    workflow_run:
        workflows: [ "Publish Release image (GHCR)" ]
        types: [ completed ]
    release:
        types: [ published ]
    workflow_dispatch:
        inputs:
            tag:
                description: "Image tag to deploy (e.g. v0.3.1 or latest)"
                required: false
                type: string

permissions:
    contents: read
    packages: read

jobs:
    deploy:
        # otomatis kalau publish-image sukses, atau manual/rilis
        if: >
            ${{
              github.event_name == 'workflow_dispatch'
              || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
              || github.event_name == 'release'
            }}
        runs-on: ubuntu-latest
        steps:
            -   name: Resolve image to deploy
                id: img
                shell: bash
                run: |
                    REPO="ghcr.io/${{ github.repository }}"
                    if [ "${{ github.event_name }}" = "release" ]; then
                      TAG="${{ github.event.release.tag_name }}"
                    elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.tag }}" ]; then
                      TAG="${{ inputs.tag }}"
                    else
                      TAG="${{ github.event.workflow_run.head_sha }}"
                    fi
                    echo "image=${REPO}:${TAG}" >> "$GITHUB_OUTPUT"

            -   name: Deploy over SSH
                uses: appleboy/ssh-action@v1
                with:
                    host: ${{ secrets.DEPLOY_HOST }}
                    username: ${{ secrets.DEPLOY_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script_stop: true
                    command_timeout: 30m
                    script: |
                        echo "Deploying IMAGE=${{ steps.img.outputs.image }}"
                        IMAGE="${{ steps.img.outputs.image }}" NAME="todolist" PORT="8080" bash /opt/todolist/deploy.sh
