name: Deploy to VM

on:
    release:
        types: [ published ]
    workflow_dispatch:
        inputs:
            tag:
                description: "Image tag to deploy (e.g. v0.3.3 or latest)"
                required: false
                type: string

permissions:
    contents: read
    packages: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Resolve image to deploy
                id: img
                shell: bash
                run: |
                    REPO="ghcr.io/${{ github.repository }}"
                    if [ "${{ github.event_name }}" = "release" ]; then
                      TAG="${{ github.event.release.tag_name }}"
                    else
                      TAG="${{ inputs.tag }}"
                      if [ -z "$TAG" ]; then
                        echo "Please provide 'tag' when running manually." >&2
                        exit 1
                      fi
                    fi
                    echo "image=${REPO}:${TAG}" >> "$GITHUB_OUTPUT"

            -   name: Deploy over SSH
                uses: appleboy/ssh-action@v1
                with:
                    host: ${{ secrets.DEPLOY_HOST }}
                    username: ${{ secrets.DEPLOY_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    command_timeout: 30m
                    script: |
                        echo "Deploying IMAGE=${{ steps.img.outputs.image }}"
                        IMAGE="${{ steps.img.outputs.image }}" NAME="todolist" PORT="8080" bash /opt/todolist/deploy.sh
