name: Publish Release image (GHCR)

on:
    release:
        types: [ published ]
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag rilis yang akan dipublish (mis. v0.2.0)"
                required: true

permissions:
    contents: read
    packages: write

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        env:
            REL_TAG: ${{ github.event.release.tag_name || inputs.tag }}
            IMAGE: ghcr.io/${{ github.repository_owner }}/todolist
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            # Set versi Maven = tag rilis, supaya /api/version bukan SNAPSHOT
            -   name: Set Maven version from tag
                run: ./mvnw -B -q versions:set -DnewVersion=${REL_TAG} versions:commit

            -   name: Build jar (skip tests)
                run: ./mvnw -B -q -DskipTests package

            -   name: Login to GHCR
                run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            -   name: Build & push images (tag rilis + latest)
                run: |
                    docker build \
                      -t "${IMAGE}:${REL_TAG}" \
                      -t "${IMAGE}:latest" .
                    docker push "${IMAGE}:${REL_TAG}"
                    docker push "${IMAGE}:latest"
