name: Publish Release image (GHCR)

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve TAG and REVISION
        id: ver
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          REV="${TAG#v}"          # strip 'v' -> 0.2.0
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "rev=$REV" >> "$GITHUB_OUTPUT"

      - name: Build & Push (tag + latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.ver.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            REVISION=${{ steps.ver.outputs.rev }}
            GIT_SHA=${{ github.sha }}
            GIT_REF=${{ steps.ver.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
